# Generated by Django 4.2.6 on 2024-09-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#FFFF00', 'Yellow'), ('#FFA500', 'Orange'), ('#FFFFFF', 'White')], default='#FFFFFF', max_length=7),
        ),
    ]
